# Generated by Django 4.2.7 on 2023-12-03 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guns', '0001_initial'),
        ('soldiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldierGun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guns.gun')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soldiers.soldier')),
            ],
        ),
    ]
