# Generated by Django 4.2.7 on 2023-12-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers', '0002_soldiergun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldier',
            old_name='nationla_id',
            new_name='national_id',
        ),
    ]
