# Generated by Django 4.2.7 on 2023-12-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers', '0004_soldierwallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldierwallet',
            old_name='wallet',
            new_name='wallet_address',
        ),
        migrations.AddField(
            model_name='soldierwallet',
            name='private_key',
            field=models.BinaryField(null=True),
        ),
    ]
